# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    include:
      - kube_apps/prometheus/values.yaml
      - kube_apps/prometheus/ingress-prometheus.yaml

pool:
  name: Default

variables:
  - template: /kube_apps/pipelines/variables/varibles.yaml

steps:

- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      helm repo add prometheus https://prometheus-community.github.io/helm-charts
      helm repo update
    failOnStderr: true
  displayName: 'Add and update Helm repository'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      kubectl apply -f $(System.DefaultWorkingDirectory)/kube_apps/prometheus/ingress-prometheus.yaml
    failOnStderr: true
    noProfile: false
  displayName: "Update ingress for prometheus."

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      helm upgrade --install prometheus \
        --namespace prometheus \
        --create-namespace \
        -f $(System.DefaultWorkingDirectory)/kube_apps/prometheus/values.yaml \
        --version $(prometheus_helm_version) \
        oci://ghcr.io/prometheus-community/charts/prometheus
    failOnStderr: false
  displayName: 'Upgrade Prometheus'

